server:
  port: 8080
spring:
  rabbitmq:
    addresses: 123.56.106.192
    username: admin
    password: admin
    virtual-host: my_vhost
  cloud:
    stream:
      bindings:
        input:
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
      binders:
        defaultRabbit:
          type: rabbit
      default-binder: rabbit
  application:
    name: consumer-1

